# for development
version: "3.8"
services:
  mongo:
    image: "mongo"
    container_name: "mongo"
    restart: always
    env_file:
      - .env
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_DOCKER_ROOT}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_DOCKER_ROOT_PASS}
      MONGO_INITDB_DATABASE: 'ramka-2'
    volumes:
      - ./docker-mongo-init-script.sh:/docker-entrypoint-initdb.d/docker-mongo-init-script.sh:ro
  mongo-express:
    image: "mongo-express"
    container_name: "mongo-express"
    restart: always
    env_file:
      - .env
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_DOCKER_ROOT}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_DOCKER_ROOT_PASS}
